// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: perfdog/fakeperfdog/perfdog.proto

package fakeperfdog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perfdog_fakeperfdog_perfdog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_perfdog_fakeperfdog_perfdog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_perfdog_fakeperfdog_perfdog_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // 名字, name
	Pic   string `protobuf:"bytes,2,opt,name=pic,proto3" json:"pic,omitempty"`     // 头像url, avatar url
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 邮箱, email
	Id    string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`       // 用户id, user id
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_perfdog_fakeperfdog_perfdog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_perfdog_fakeperfdog_perfdog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_perfdog_fakeperfdog_perfdog_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_perfdog_fakeperfdog_perfdog_proto protoreflect.FileDescriptor

var file_perfdog_fakeperfdog_perfdog_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x65, 0x72, 0x66, 0x64, 0x6f, 0x67, 0x2f, 0x66, 0x61, 0x6b, 0x65, 0x70, 0x65,
	0x72, 0x66, 0x64, 0x6f, 0x67, 0x2f, 0x70, 0x65, 0x72, 0x66, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x65,
	0x72, 0x66, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x56, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x32, 0x65, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x44, 0x6f, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x69, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x61, 0x6b,
	0x65, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x61, 0x6b, 0x65,
	0x2e, 0x70, 0x65, 0x72, 0x66, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x42, 0x10, 0x50, 0x01, 0x5a, 0x0c, 0x2f,
	0x66, 0x61, 0x6b, 0x65, 0x70, 0x65, 0x72, 0x66, 0x64, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_perfdog_fakeperfdog_perfdog_proto_rawDescOnce sync.Once
	file_perfdog_fakeperfdog_perfdog_proto_rawDescData = file_perfdog_fakeperfdog_perfdog_proto_rawDesc
)

func file_perfdog_fakeperfdog_perfdog_proto_rawDescGZIP() []byte {
	file_perfdog_fakeperfdog_perfdog_proto_rawDescOnce.Do(func() {
		file_perfdog_fakeperfdog_perfdog_proto_rawDescData = protoimpl.X.CompressGZIP(file_perfdog_fakeperfdog_perfdog_proto_rawDescData)
	})
	return file_perfdog_fakeperfdog_perfdog_proto_rawDescData
}

var file_perfdog_fakeperfdog_perfdog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_perfdog_fakeperfdog_perfdog_proto_goTypes = []interface{}{
	(*Token)(nil),    // 0: com.fake.perfdog.proto.Token
	(*UserInfo)(nil), // 1: com.fake.perfdog.proto.UserInfo
}
var file_perfdog_fakeperfdog_perfdog_proto_depIdxs = []int32{
	0, // 0: com.fake.perfdog.proto.PerfDogService.loginWithToken:input_type -> com.fake.perfdog.proto.Token
	1, // 1: com.fake.perfdog.proto.PerfDogService.loginWithToken:output_type -> com.fake.perfdog.proto.UserInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_perfdog_fakeperfdog_perfdog_proto_init() }
func file_perfdog_fakeperfdog_perfdog_proto_init() {
	if File_perfdog_fakeperfdog_perfdog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_perfdog_fakeperfdog_perfdog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_perfdog_fakeperfdog_perfdog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_perfdog_fakeperfdog_perfdog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_perfdog_fakeperfdog_perfdog_proto_goTypes,
		DependencyIndexes: file_perfdog_fakeperfdog_perfdog_proto_depIdxs,
		MessageInfos:      file_perfdog_fakeperfdog_perfdog_proto_msgTypes,
	}.Build()
	File_perfdog_fakeperfdog_perfdog_proto = out.File
	file_perfdog_fakeperfdog_perfdog_proto_rawDesc = nil
	file_perfdog_fakeperfdog_perfdog_proto_goTypes = nil
	file_perfdog_fakeperfdog_perfdog_proto_depIdxs = nil
}
